log_path: /Users/liyanguo/code/GoglandProjects/http_server/logs
log_name: server
log_file_size: 100000000
log_file_count: 100
http_listen_port: :51204
http_template_path: /Users/liyanguo/code/GoglandProjects/http_server/templates
http_cookie_secret: 5TYHJMGHUIHNrfvgho-0ugbhyhhhjf5r
http_session_id: secret_session_id
http_access_time: secret_access_time
http_session_timeout: 900
upload_data_path: /Users/liyanguo/code/GoglandProjects/http_server/data
upload_max_size: 1000000000
sqlite_db_path: /Users/liyanguo/code/GoglandProjects/http_server/db/data.db
oauth_app_id: app_id
oauth_app_secret: app_secret
oauth_redirect_url: my_url
oauth_user_url: user_url
oauth_auth_url: auth_url
oauth_token_url: token_url